version: '3.3'

services:
  pb:
    container_name: pb
    build:
      context: .
      dockerfile: Dockerfile.pb
    ports:
      - 8090:8090
    volumes:
      - ./tmp/pb_data:/app/tmp/pb_data
      - ./main.go:/app/main.go
      - ./pkgs:/app/pkgs
    env_file:
      - .env
  vue:
    container_name: vue
    build:
      context: .
      dockerfile: Dockerfile.vue
    ports:
      - 5173:5173
    volumes:
      - ./src:/app/src
    environment:
      - VITE_POCKETBASE_URL=http://localhost:8090
  