version: '3.3'

volumes:
  vue_assets:

services:
  pocketbase:
    container_name: pb-server
    build:
      context: .
      dockerfile: Dockerfile.pb
    ports:
      - 8080:8080
    volumes:
      - ./pb_data:/pb_data
      - vue_assets:/pb_public
    env_file:
      - .env
  vuewatcher:
    container_name: vue-watcher
    build:
      context: .
      dockerfile: Dockerfile.vue
    volumes:
      - ./src:/src
      - vue_assets:/dist
  